export enum NotificationType {
  CERTIFICATE_EXPIRY_WARNING = 'CERTIFICATE_EXPIRY_WARNING',
  CERTIFICATE_EXPIRY_CRITICAL = 'CERTIFICATE_EXPIRY_CRITICAL',
  CERTIFICATE_EXPIRED = 'CERTIFICATE_EXPIRED',
  AUDIT_SCHEDULED = 'AUDIT_SCHEDULED',
  AUDIT_SUBMITTED = 'AUDIT_SUBMITTED',
  AUDIT_APPROVED = 'AUDIT_APPROVED',
  AUDIT_REJECTED = 'AUDIT_REJECTED',
  COORDINATOR_ASSIGNED = 'COORDINATOR_ASSIGNED',
  COMPLIANCE_SCORE_LOW = 'COMPLIANCE_SCORE_LOW',
  SYSTEM = 'SYSTEM',
}
